#!/bin/sh

set -e

$JAVA_HOME/bin/javac -classpath lib/csv4j-0.4.0.jar:lib/geomason.1.5.jar:lib/jcommon-1.0.16.jar:lib/jfreechart-1.0.9.jar:lib/jts-1.13.jar:lib/mason.19.jar  -d classes src/*.java

$JAVA_HOME/bin/java -Xmx12288m -cp classes:lib/csv4j-0.4.0.jar:lib/geomason.1.5.jar:lib/jcommon-1.0.16.jar:lib/jfreechart-1.0.9.jar:lib/jts-1.13.jar:lib/mason.19.jar EbolaWithUI
